# This rule is not used by the project aitrigram itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over aitrigram.cliver-project.github.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aitrigram
    app.kubernetes.io/managed-by: kustomize
  name: llmengine-admin-role
rules:
- apiGroups:
  - aitrigram.cliver-project.github.io
  resources:
  - llmengines
  verbs:
  - '*'
- apiGroups:
  - aitrigram.cliver-project.github.io
  resources:
  - llmengines/status
  verbs:
  - get
