apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: aitrigram.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - displayName: LLMEngine
      kind: LLMEngine
      name: llmengines.aitrigram.ihomeland.cn
      version: v1
    - description: |-
        ModelRepository is the Schema for the modelrepositories API
        ModelRepository is a cluster wide CRD so that models can be shared across namespaces.
      displayName: Model Repository
      kind: ModelRepository
      name: modelrepositories.aitrigram.ihomeland.cn
      version: v1
  description: The operator to undle AI inference providers
  displayName: aitrigram
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ai
  - agent
  - llm
  - vllm
  links:
  - name: Aitrigram
    url: https://aitrigram.domain
  maintainers:
  - email: aoingl@gmail.com
    name: lgao
  maturity: alpha
  provider:
    name: aitrigram
    url: https://github.com/gaol
  version: 0.0.0
