---
apiVersion: aitrigram.cliver-project.github.io/v1
kind: LLMEngine
metadata:
  labels:
    app.kubernetes.io/name: aitrigram
    app.kubernetes.io/managed-by: kustomize
  name: ollama-engine-full
spec:
  # the docker image for this LLMEngine
  engineType: "ollama"
  servicePort: 8080
  image: "ollama/ollama:latest"
  port: 11434
  modelDeploymentTemplate:
    downloadImage: "ollama/ollama:latest"
    downloadScripts: "ollama serve & sleep 10 && ollama pull {{ .ModelName }}"
    args:
      - "/bin/ollama"
      - "serve"
    storage:
      cacheDir:
        path: "/cache"
        hostPath:
          path: "/ollama/cache"
      modelsDir:
        path: "/models_dir"
        emptyDir: {}
    env:
      - name: "OLLAMA_MODELS"
        value: "/models_dir"
---
apiVersion: aitrigram.cliver-project.github.io/v1
kind: ModelRepository
metadata:
  labels:
    app.kubernetes.io/name: aitrigram
    app.kubernetes.io/managed-by: kustomize
  name: modelrepository-sample
spec:
  # modelName defaults to metadata.name (modelrepository-sample) if not specified
  source:
    origin: ollama
    modelId: gemma3-1b
  storage:
    path: /models
    emptyDir: {}
  autoDownload: true