name: CI for AITrigram

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "**"

jobs:
  ci-test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      # - name: Run linter
      #   uses: golangci/golangci-lint-action@v6
      #   with:
      #     version: v1.63.4

      - name: Running Tests
        run: |
          go mod tidy
          make all

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          kubernetes-version: stable

      - name: Running Test e2e
        env:
          E2E_DUMP_LOGS: "true"
        run: |
          go mod tidy
          make test-e2e

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata for tags
        id: meta
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/cliver-project/aitrigram-controller
          tags: |
            type=ref,event=tag

      - name: Build and push image on Push to main
        uses: docker/build-push-action@v6
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/cliver-project/aitrigram-controller:latest
            ghcr.io/cliver-project/aitrigram-controller:${{ github.sha }}

      - name: Build and push image on Tag
        uses: docker/build-push-action@v6
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
